---
title: "Assignment 1"
highlight-style: arrow-dark
---


# Assignment 1

```{r}
1 + 1
```

My first assignment has two parts.

## (a)

## (b)

-
```{r}

custom_function <- function(data){
  if(!is.vector(data)){
    print("Girdi vektor olmalidir.")}
  else {
    average<-mean(data)
    max<-max(data)
    min<-min(data)
    sd<-sd(data)
    data_list <- list(avg=average,max=max,min=min,sd=sd)
    return(data_list)}
}


for (i in colnames(mtcars) ){
  cars_attributes <- c(mtcars[[i]])
  result1<-custom_function(cars_attributes)
  result2<-paste(i,names(result1),result1)
  print(result2)
}


```


-
```{r}
custom_function <- function(data){
  if(!is.vector(data)){
    print("Girdi vektor olmalidir.")}
  else {
    average<-mean(data)
    max<-max(data)
    min<-min(data)
    sd<-sd(data)
    data_list <- list(avg=average,max=max,min=min,sd=sd)
    return(data_list)}
}
print(apply(mtcars,2,custom_function))



  
```

## (c)


```{r}

library(dslabs)
na_example
Na_count<-sum(is.na(na_example))
Na_count

data_na <- replace(na_example, is.na(na_example), 660)
data_na
Na_count2<-sum(is.na(data_na))
Na_count2

count_660 <- sum(data_na==660)
count_660

```
